dataSources:
  - name: data-base-1
    strategy: postgres
    url: jdbc:postgresql://localhost:5432/first_database?createDatabaseIfNotExist=true
    user: postgres
    password: password
    table: users
    mapping:
      id: user_id
      username: login
      name: first_name
      surname: last_name
  - name: data-base-2
    strategy: postgres
    url: jdbc:postgresql://localhost:5432/second_database?createDatabaseIfNotExist=true
    user: postgres
    password: password
    table: user_table
    mapping:
      id: ldap_login
      username: ldap_login
      name: name
      surname: surname

